#!/usr/bin/env python
"""
This script can be used to print out the rows of a CSV file matching one of the columns.
"""

import os
import sys

if len(sys.argv) != 3:
    sys.stderr.write("Usage: csv-rows csvfile idfile\n")
    sys.exit(1)

csvfile = open(sys.argv[1], 'r').readlines()
idfile = open(sys.argv[2], 'r').readlines()

for id in idfile:

    if not id:
        continue

    matched_row = [row for row in csvfile if row.startswith(id.strip())]

    if matched_row:
        sys.stdout.write(matched_row[0])
    else:
        pass

sys.exit(0)


