#!/usr/bin/env python3.6

from subprocess import call
import argparse

if __name__ == '__main__':
	description = 'Merge pdfs together.'

	parser = argparse.ArgumentParser(description = description)

	parser.add_argument(
		'-o',
		'--output',
		type = str,
		help = 'Output file name',
		default = 'merged-output.pdf')

	parser.add_argument(
		'-i',
		'--inputs',
		type = str,
		nargs = '+',
		help = 'List of input files to merge',
		required = True)

	args = parser.parse_args()

	call(['gs', '-dBATCH', '-dNOPAUSE', '-q', '-sDEVICE=pdfwrite', f'-sOutputFile={args.output}'] + args.inputs)

	#call([gs -dNOPAUSE -dBATCH -dFirstPage=2 -dLastPage=2 -sDEVICE=pdfwrite -sOutputFile=dest.pdf -f src.pdf])

